### PR TITLE
added support for immutable processing

### PR DESCRIPTION
**Pull request by sdellysse**
I needed to run this lib against an array that I should not modify. I added a new function `unique.immutable` that keeps all semantics of `unique` except it doesn't modify the input array. Performance will be slightly lessened but not enough to matter in my case.

### CODE REVIEW

**Comment by sdellysse** [comment]
ping

**Comment by jonschlinkert** [comment]
Hi, thanks for the pr @shawndellysse, sorry I didn't see this earlier. I'll take asap, thanks!

**Comment by sdellysse** [comment]
Thanks!

**Comment by jonschlinkert** [comment]
Really sorry for the extremely late merge!

**Comment by jonschlinkert** [comment]
@shawndellysse this was a superb pr. Comprehensive tests, beautifully coded, docs as well. I really appreciate it, and again I'm sorry it took so long. 

Also, I made you a collab on this lib. I'd be happy to add you to npm as well if you want to give me your username. thanks again!

**Comment by jonschlinkert** [comment]
almost forgot, published and git tagged as 0.3.2. Since there were no changes to the existing API, a patch should be fine

**Comment by es128** [comment]
Hey @jonschlinkert - happened to come across this following your tweet about it. 

Hopefully this isn't overly pedantic, but if you want to follow the semver spec it seems like this should have been a minor version bump, which indicates feature additions with no breaking changes to the existing API. Patches are supposed to indicate bug fixes with no changes to the api footprint. 

Otoh technically you're fine since anything goes in the 0.x range. 

Just thought it was worth a quick mention to help guide any future semver decisions.

**Comment by jonschlinkert** [comment]
You're absolutely right. I guess I'm slipping into absentmindedness.

Glad to see you btw, I was just wondering how you were doing

**Comment by es128** [comment]
Doing fine, just spending more time on other hobbies lately.

Hope all is well with you 😀

**Comment by jonschlinkert** [comment]
good to hear. yeah I'm doing well, thanks.

**Pull request merged**
